In [2]:
#from google.colab import drive
#drive.mount('/content/drive')

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
df = pd.read_csv("/content/OSX_DS_assignment.csv")

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df


user_name   country  \
0       @kerinokeefe     Italy   
1         @vossroger  Portugal   
2        @paulgwine         US   
3                NaN        US   
4        @paulgwine         US   
...              ...       ...   
103317           NaN   Germany   
103318   @paulgwine         US   
103319    @vossroger    France   
103320    @vossroger    France   
103321    @vossroger    France   

                                             review_title  \
0                       Nicosia 2013 Vulkà Bianco  (Etna)   
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           Rainstorm 2013 Pinot Gris (Willamette Valley)   
3       St. Julian 2013 Reserve Late Harvest Riesling ...   
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...   
...                                                   ...   
103317  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...   
103318                  Citation 2004 Pinot Noir (Oregon)   
103319  Domaine Gresser 2013 Kritt Gewurztraminer (Als...   
103320      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)   
103321  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...   

                                       review_description  \
0       Aromas include tropical fruit, broom, brimston...   
1       This is ripe and fruity, a wine that is smooth...   
2       Tart and snappy, the flavors of lime flesh and...   
3       Pineapple rind, lemon pith and orange blossom ...   
4       Much like the regular bottling from 2012, this...   
...                                                   ...   
103317  Notes of honeysuckle and cantaloupe sweeten th...   
103318  Citation is given as much as a decade of bottl...   
103319  Well-drained gravel soil gives this wine its c...   
103320  A dry style of Pinot Gris, this is crisp with ...   
103321  Big, rich and off-dry, this is powered by inte...   

                                   designation  points  price  \
0                                 Vulkà Bianco      87    NaN   
1                                     Avidagos      87   15.0   
2                                          NaN      87   14.0   
3                         Reserve Late Harvest      87   13.0   
4           Vintner's Reserve Wild Child Block      87   65.0   
...                                        ...     ...    ...   
103317  Brauneberger Juffer-Sonnenuhr Spätlese      90   28.0   
103318                                     NaN      90   75.0   
103319                                   Kritt      90   30.0   
103320                                     NaN      90   32.0   
103321           Lieu-dit Harth Cuvée Caroline      90   21.0   

                 province             region_1           region_2  \
0       Sicily & Sardinia                 Etna                NaN   
1                   Douro                  NaN                NaN   
2                  Oregon    Willamette Valley  Willamette Valley   
3                Michigan  Lake Michigan Shore                NaN   
4                  Oregon    Willamette Valley  Willamette Valley   
...                   ...                  ...                ...   
103317              Mosel                  NaN                NaN   
103318             Oregon               Oregon       Oregon Other   
103319             Alsace               Alsace                NaN   
103320             Alsace               Alsace                NaN   
103321             Alsace               Alsace                NaN   

                                          winery         variety  
0                                        Nicosia     White Blend  
1                            Quinta dos Avidagos  Portuguese Red  
2                                      Rainstorm      Pinot Gris  
3                                     St. Julian        Riesling  
4                                   Sweet Cheeks      Pinot Noir  
...                                          ...             ...  
103317  Dr. H. Thanisch (Erben Müller-Burggraef)        R

In [7]:
df2=df.drop(columns=['user_name','review_title','review_description','winery','designation','region_2'])

In [8]:
df2_per=df2.isnull().sum()/df.shape[0]*100
df2_per

country      0.037746
points       0.000000
price        6.739126
province     0.037746
region_1    15.551383
variety      0.000000
dtype: float64

In [9]:
df2.isnull().sum()

country        39
points          0
price        6963
province       39
region_1    16068
variety         0
dtype: int64

In [10]:
mean1=df2['price'].mean()
mean1

36.78122437966355

In [11]:
df2['price']=df2['price'].fillna(mean1)

In [12]:
df2=df2.fillna(method='ffill')

In [13]:
df2.head()

country  points      price           province             region_1  \
0     Italy      87  36.781224  Sicily & Sardinia                 Etna   
1  Portugal      87  15.000000              Douro                 Etna   
2        US      87  14.000000             Oregon    Willamette Valley   
3        US      87  13.000000           Michigan  Lake Michigan Shore   
4        US      87  65.000000             Oregon    Willamette Valley   

          variety  
0     White Blend  
1  Portuguese Red  
2      Pinot Gris  
3        Riesling  
4      Pinot Noir

In [14]:
df2.isnull().sum()

country     0
points      0
price       0
province    0
region_1    0
variety     0
dtype: int64

In [15]:
df2.head()

country  points      price           province             region_1  \
0     Italy      87  36.781224  Sicily & Sardinia                 Etna   
1  Portugal      87  15.000000              Douro                 Etna   
2        US      87  14.000000             Oregon    Willamette Valley   
3        US      87  13.000000           Michigan  Lake Michigan Shore   
4        US      87  65.000000             Oregon    Willamette Valley   

          variety  
0     White Blend  
1  Portuguese Red  
2      Pinot Gris  
3        Riesling  
4      Pinot Noir

Encoding


In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
label_encoder = LabelEncoder()
df2['country'] = label_encoder.fit_transform(df2['country'])
df2['province'] = label_encoder.fit_transform(df2['province'])
df2['region_1	'] = label_encoder.fit_transform(df2['region_1'])

In [18]:
df2.head()

country  points      price  province             region_1         variety  \
0       19      87  36.781224       282                 Etna     White Blend   
1       28      87  15.000000        91                 Etna  Portuguese Red   
2       37      87  14.000000       225    Willamette Valley      Pinot Gris   
3       37      87  13.000000       183  Lake Michigan Shore        Riesling   
4       37      87  65.000000       225    Willamette Valley      Pinot Noir   

   region_1\t  
0         364  
1         364  
2        1044  
3         476  
4        1044

In [19]:
x=df2.drop(["variety","region_1"],axis=1)
y=df2["variety"]

In [20]:
y=label_encoder.fit_transform(y)

In [21]:
x

country  points      price  province  region_1\t
0            19      87  36.781224       282         364
1            28      87  15.000000        91         364
2            37      87  14.000000       225        1044
3            37      87  13.000000       183         476
4            37      87  65.000000       225        1044
...         ...     ...        ...       ...         ...
103317       14      90  28.000000       194          16
103318       37      90  75.000000       225         673
103319       12      90  30.000000        11          16
103320       12      90  32.000000        11          16
103321       12      90  21.000000        11          16

[103322 rows x 5 columns]

#spliting test and train data

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2)

#Harsh(Random forest classification, SVM)

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rndfr_classifier=RandomForestClassifier(n_estimators=100, max_depth=15, random_state=30)
rndfr_classifier.fit(x_train,y_train)

RandomForestClassifier(max_depth=15, random_state=30)

In [26]:
y_pred=rndfr_classifier.predict(x_test)


In [27]:
accuracy=rndfr_classifier.score(x_test,y_test)
accuracy

0.5703363174449553

In [28]:
from sklearn.svm import SVC

In [ ]:
svm_classifier=SVC(kernel='poly')
svm_classifier.fit(x_train,y_train)

In [ ]:
y_pred=svm_classifier.predict(x_test)

In [ ]:
accuracy=svm_classifier.score(x_test,y_test)
accuracy

#Rishabh(decision tree cart, K-means clustering)

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score


In [29]:
dtc=DecisionTreeClassifier( min_samples_leaf=20,max_depth=20)
dtc.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=20, min_samples_leaf=20)

In [30]:
y_pre=dtc.predict(x_test)
y_pre

array([ 1, 25, 14, ...,  3, 19,  0])

In [31]:
dtc.score(x_test,y_test)


0.5524800387127994

In [32]:
dtr=DecisionTreeRegressor(max_depth=12)
dtr.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=12)

In [33]:
y_p=dtr.predict(x_test)
y_p

array([ 5.81967213, 14.33014354, 12.54326241, ..., 12.188     ,
       17.61206897,  9.62542955])

In [35]:
dtr.score(x_test,y_test)

0.3960670555716568

In [36]:
gb=GradientBoostingClassifier()
gb.fit(x_train,y_train)

KeyboardInterrupt: ignored

In [ ]:
y_pr=gb.predict(x_test)
y_pr

In [ ]:
gb.score(x_test,y_test)

## DEVANSH

In [37]:
from sklearn.linear_model import Ridge
from sklearn.ensemble import AdaBoostClassifier

In [38]:
model = Ridge(alpha = 0.5)

In [39]:
model.fit(x_train, y_train)

Ridge(alpha=0.5)

In [40]:
y_pred = model.predict(x_test)

In [41]:
accuracy= model.score(x_test, y_test)
print("\n\nModel score : ", accuracy)



Model score :  0.06271975644592731


harshit

In [42]:
from sklearn.linear_model import LinearRegression
lr_clf=LinearRegression()
lr_clf.fit(x_train,y_train)
lr_clf.score(x_test,y_test)

0.06271975634613292

In [43]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=10)
knn_clf.fit(x_test,y_test)
knn_clf.score(x_test,y_test)


0.5575127026373095

In [44]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=0)

cross_val_score(KNeighborsClassifier(), x, y, cv=cv)

array([0.51246068, 0.51429954, 0.51705783, 0.52020324, 0.51371885,
       0.52136463, 0.51894508, 0.51909025, 0.52383257, 0.51792887])

In [45]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=0)
cross_val_score(LinearRegression(), x, y, cv=cv)

array([0.05962511, 0.0594231 , 0.05615819, 0.06150471, 0.05779712,
       0.05980809, 0.05965212, 0.06278212, 0.06274024, 0.06773975])

In [46]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score
modelsm = {
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'svc':SVC(),
    'DecisionTree':DecisionTreeClassifier(),
    'GradientBoosting':GradientBoostingClassifier(),
    'AdaBoost':AdaBoostClassifier(),
    'Ridge':Ridge(),
    'DecisionTreeReg':DecisionTreeRegressor(),
    'LinearRegression':LinearRegression(),
    ' KNeighbors': KNeighborsClassifier()
}
best_f1 = 0.0
best_model = None

for model_name, model in modelsm.items():

    f1_scores = cross_val_score(model, x, y, cv=5, scoring='f1_macro')

    avg_f1 = f1_scores.mean()


    if avg_f1 > best_f1:
        best_f1 = avg_f1
        best_model = model_name

print("Best F1 score:", best_f1)
print("Best model:", best_model)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:794: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 115, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1146, in f1_score
    return fbeta_score(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1287, in fbeta_score
    _, _, f, _ = precision_recall_fscore_support(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1573, in precision_recall_fscore_support
  

Best F1 score: 0.5490441926968783
Best model: Random Forest
